### ISSUE TITLE
从管理员页面切换到一个没有启用的用户后无法返回管理员身份问题

### ISSUE THREAD

**Issue by heyuan0028** [Anankke/ss-panel-v3-mod_Uim#407]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题
貌似在demo站点无法关闭一个用户？但是可以修改其他信息
<img width="659" alt="qq20181203-125653 2x" src="https://user-images.githubusercontent.com/30433964/49353864-fbb4ff00-f6fa-11e8-939c-a6f3992d38ca.png">

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容
commit dff6f9064e8821293d925a8970c79607f72470c5
Author: NimaQu <i@nimaqu.com>
Date:   Mon Dec 3 01:59:28 2018 +0800

    fix : バカ SakuraSa233

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

如果另开一个无痕页面，进入后台，恢复账户启用后，可正常跳转回管理员身份

**申请添加新的特性或功能或者好的想法**

**Comment by NimaQu** [comment]
@heyuan0028 真会玩.webp

**Comment by CGDF-Github** [comment]
除本issue以外，【禁用用户】还会导致【一旦登入便无法登出】等BUG。就目前来说，请尽量避免使用【禁用用户】功能
