### ISSUE TITLE
能否实现节点限速取最小值呢

### ISSUE THREAD

**Issue by llllleeee** [Anankke/ss-panel-v3-mod_Uim#448]
举例：单端口多用户，比如某节点限速10m 用户限速100m 取节点限速的10m 而不是取用户限速

**Comment by xcxnig** [comment]
@ligengwen 现在就是

**Comment by ligengwen** [comment]
@xcxnig 大佬你现在使用的是哪个后端脚本能否分享给我一下

**Comment by SuicidalCat** [comment]
@ligengwen https://github.com/SuicidalCat/Airport-toolkit

**Comment by CGDF-Github** [comment]
@xcxnig 修正：后端是取最大值的

**Comment by yangyzp** [comment]
后端取大值，感觉这个设计不太合理。。
比如：套餐限速20M。（针对大部分节点）
但是某些特殊节点（比如用于游戏的节点），节点限速3M。
如果用游戏节点的时候，应该取3m的限速，才合理~~

**Comment by laurieryayoi** [comment]
@yangyzp 这么巧，我也觉得

**Comment by ligengwen** [comment]
@yangyzp 对，就是这个问题

**Comment by JohnFreeman9** [comment]
@ligengwen ssp最初的设计就是取最大值以免出现一方未设置取小为0反而导致限速失效的情况，如果你希望解决这个问题，请自行完整修改面板和服务端关于限速部分的逻辑。

**Comment by CGDF-Github** [comment]
> @ligengwen ssp最初的设计就是取最大值以免出现一方未设置取小为0反而导致限速失效的情况，如果你希望解决这个问题，请自行完整修改面板和服务端关于限速部分的逻辑。

首先这种情况完全不成立，
以及，如果有取小限速需求的可以自行根据 https://github.com/Anankke/shadowsocks/pull/1/files 进行修改
