### ISSUE TITLE
继续增加tg机器人的功能及建议在管理面板里增加错误日志

### ISSUE THREAD

**Issue by SaylerYang** [Anankke/ss-panel-v3-mod_Uim#489]
上次增加tg机器人的订阅后，反馈良好，希望再增加重置订阅的功能
同时希望增加错误日志，方便查看邮件发送，节点等报错信息的具体内容。

**Comment by Anankke** [comment]
@SaylerYang pr welcome

**Comment by eeeeLeeee** [comment]
重置订阅一般仅在链接泄露的时候用吧？我自己从来没用过。难道账号还经常万人骑？

**Comment by CGDF-Github** [comment]
这个issue就很有官腔，很有领导风范，深得官场精髓，学习学习。

**Comment by NimaQu** [comment]
@CGDF-Github 哪个公司的产品经理？

**Comment by xcxnig** [comment]
@SaylerYang 得知这个建议后，开发组高度重视，有关人员正在加班加点进行开发调试工作。

**Comment by SaylerYang** [comment]
感谢同志们的努力付出，我替海里保安公司向你们表示最诚挚的问候和最衷心的邀请.

**Comment by rico93** [comment]
咕咕
