### ISSUE TITLE
mac端 订阅失败

### ISSUE THREAD

**Issue by zhangyubushiyu** [Anankke/ss-panel-v3-mod_Uim#492]
mac有问题。其他都正常

**Comment by CGDF-Github** [comment]
哦可能是我写的BUG

**Comment by CGDF-Github** [comment]
（立即尝试认罪

**Comment by CGDF-Github** [comment]
不对，订阅失败和我没关系，我也没在MacOS上复现此问题，看来只是你自己不会用（立即翻供

**Comment by zhangyubushiyu** [comment]
> 不对，订阅失败和我没关系，我也没在MacOS上复现此问题，看来只是你自己不会用（立即翻供

你MAC端能不能测试一下。http://www.ss-233.tk/link/s5oOaTiTBoWPBWGv?mu=0 这是我的订阅链接。看是我的个例还是都这样子。

**Comment by kotomei** [comment]
@zhangyubushiyu 草

**Comment by CGDF-Github** [comment]
请把http改成https
