### ISSUE TITLE
你希望index/#/user/panel页面有什么功能

### ISSUE THREAD

**Issue by laurieryayoi** [Anankke/ss-panel-v3-mod_Uim#493]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**

![img](https://puu.sh/Cw2Rf/0d37045a6d.png)

{baseurl}/#/user/panel 为首页用vue.js重写后的登录后界面。
如各位所见是个没开工的页面，本来是为了防止用户登录后后退又回到登录页的，写着写着好像变成了一个可以扩展的大工程……
现在只是把以前的用户中心首页的接口用在这里，不过其他页面的功能也不是不能加进来。
所以你们觉得什么可以有，我只后做这个页面的时候会考虑把功能加进去

**Comment by PengCaiPC** [comment]
围观

**Comment by zhoud2001** [comment]
@PengCaiPC 围观

**Comment by wxlost** [comment]
放个特别公告,和登录后的公告区分开?..emm
或者这里可以插入广告?

**Comment by Runc2333** [comment]
希望注册的时候请求邮箱验证码要求先完成reCAPTCHA或者geetest，避免大量发送垃圾邮件(发了5k封无效地址的惨痛经历)。
实现的话我自己试了下，好像也就复制粘贴一下的事情()

**Comment by zhoud2001** [comment]
@Runc2333 xmdys超大机场😐

**Comment by Runc2333** [comment]
等等看错了...这个是index（）

**Comment by Runc2333** [comment]
立即自删

**Comment by lenovoy450** [comment]
@RebornForPower  建立立刻给项目组捐赠114514个bitcoin用于支付测试。

**Comment by galaxychuck** [comment]
@RebornForPower 建議增加線下PY交易功能

**Comment by laurieryayoi** [comment]
> 建议增加bitcoin支付功能

这是后端的事，和前端页面没关系

**Comment by ruich97** [comment]
@glzjin test

**Comment by stardock** [comment]
> 
> 
> 建议增加一键跑路功能  

这个功能已经存在了，，，，  
config.php中 site title 修改为 `跑路` 即达到效果。话说跑路页面还挺好看的。

**Comment by ruich97** [comment]
@stardock 谁跑路一个我看看？

**Comment by Hitiko** [comment]
@stardock 快做个跑路demo站，，，

**Comment by AIDE741500926** [comment]
建议可以显示以日，周，月，年的流量详情流水查询，用户自查用，粒点很神奇，但是粒点看起来也不是特别直观，看大佬有啥想法没

**Comment by laurieryayoi** [comment]
@AIDE741500926 不做，除非有API直接给这些数据

**Comment by yry0008** [comment]
加上一个主服务器负载情况……

**Comment by laurieryayoi** [comment]
> 加上一个主服务器负载情况……

你要让用户看到主服务器负载干嘛？

**Comment by AIDE741500926** [comment]
我来提个想法吧，给用户中心添加个电台功能，可以听下二次元😅音乐

**Comment by ZHQSM** [comment]
手机端 浏览器自适应 就目前看  手机常用浏览器都会卡在 用户dome页  进不去

**Comment by laurieryayoi** [comment]
@ZHQSM 小米6 自带浏览器、via和IP6S 的safari都没问题。 如果你用的是内核版本很低的浏览器那没办法。 适配手机屏幕等功能做的差不多再说吧

**Comment by ZHQSM** [comment]
@laurieryayoi 我用了小米mix2s 自带浏览器 并进行了清除缓存的处理同时关闭了广告过滤  还装了最新的QQ浏览器 和uc浏览器 都是一样的结果  小米6 浏览器 应该和mix2s 应该是同样的版本 我用Chrome 倒是没这情况。我怕是我前端搭建出错，我又用手机登录演示站  问题一样~~ 难道就我手机这样？

**Comment by SuicidalCat** [comment]
@ZHQSM 那用chrome不就好了？

**Comment by laurieryayoi** [comment]
@ZHQSM 测了一下，小米默认浏览器内核不支持vuex，请使用chrome或者via等采用较新webkit内核的浏览器。后期会考虑使用babel编译解决兼容问题

**Comment by ZHQSM** [comment]
@laurieryayoi 能不能先出个临时方案 判断内核 支持vuex正常访问新首页 不支持的跳转至原来的首页 不知道能否实现？

**Comment by laurieryayoi** [comment]
@ZHQSM 等我充完天然气回去看看

**Comment by lenovoy450** [comment]
自己把oldindex拿出来呗.

**Comment by ZHQSM** [comment]
@lenovoy450 我现在就是这么做的~~

**Comment by ZHQSM** [comment]
建议：订阅节点增加对 ['mergeSub']值的判断   ，连接信息增加 单端口多用户的信息。 栏目导航横向分布排列 点击切换显示信息。
ps：测试了最新版 小米自带浏览器成功判定跳转至oldindex  但QQ浏览器和uc依然是进入新首页 ，在进入用户界面卡住。 是不是可以这么理解 QQ 、uc 支持vuex，但另外的不支持，所以卡住了。 昨天测试小米浏览器是卡住在首页 和QQ、uc卡的地方不一样。

**Comment by ZHQSM** [comment]
不知道 大人的小米6 自带浏览器 在老版登录页 能否正常登录成功  我这个好像是在12月的一次UI更新中 就开始点登录没反应了  粒子效果也加载不了~

**Comment by laurieryayoi** [comment]
> 不知道 大人的小米6 自带浏览器 在老版登录页 能否正常登录成功 我这个好像是在12月的一次UI更新中 就开始点登录没反应了 粒子效果也加载不了~

老版本加载不了jsdelivr，自行换CDN或者下载到vps本地调用

**Comment by laurieryayoi** [comment]
> 建议：订阅节点增加对 ['mergeSub']值的判断 ，连接信息增加 单端口多用户的信息。 栏目导航横向分布排列 点击切换显示信息。
> ps：测试了最新版 小米自带浏览器成功判定跳转至oldindex 但QQ浏览器和uc依然是进入新首页 ，在进入用户界面卡住。 是不是可以这么理解 QQ 、uc 支持vuex，但另外的不支持，所以卡住了。 昨天测试小米浏览器是卡住在首页 和QQ、uc卡的地方不一样。

UC和qq有毒好吧，不支持了，请用chrome，嫌重就装via，或者其他没被开发的人下毒的浏览器

**Comment by GeekQu** [comment]
看完上面的建议，`/user` 已经可以撤下了

**Comment by dejavui** [comment]
用户排行？
用户是否公开自己在本站累积流量，最快速率（今日用户累积流量TOP100）
最常用地点（地图模糊表示）好像有点查水表节奏:(

**Comment by limbodiyu** [comment]
添加谷歌广告？月入.......

**Comment by Hitiko** [comment]
@limbodiyu 月入114514元（即答）

**Comment by ruich97** [comment]
@taizi-tp 一键自首

**Comment by mxihan** [comment]
@limbodiyu 不如搞个一键出道功能

**Comment by ZHQSM** [comment]
我又来反馈问题了  @NimaQu @SukkaW加入了判断代码，名字取了个fuck。。。 第一@laurieryayoi 前天做了
较低版本webkit浏览器支持的处理，测试 uc和qq浏览器是可以完美运行的。 而miui原来做了跳转旧首页的处理，因为没取消，直接访问会有两次fuck。。。最后也不能调用新的推荐下载浏览器选项框。如果删除跳转代码，miui会卡在首页。 
第二 做了测试判断代码 手机标签mqq和qq应该是弄反了 mqq是QQ浏览器 qq是手机QQ 浏览器。
第三  建议新用户中心 端口速率 和在线设备数 的显示信息和 管理版本的显示信息保持同步，如果是无限制不是显示0而是显示无限制。

**Comment by limbodiyu** [comment]
> @limbodiyu 干脆和菠菜涩情网站合作搞ad好不好，一步到位

那还开什么飞机，直接卖涩情用品怎么说。

**Comment by SuicidalCat** [comment]
@limbodiyu

**Comment by SukkaW** [comment]
@ZHQSM 说清楚哪个是哪个
现在有三个玩意：

- 手机QQ，内置的浏览器
- 手机上的 QQ浏览器
- PC 上的 QQ 浏览器

你想说谁的 UA 是什么？

**Comment by zhangyubushiyu** [comment]
> > 建议增加一键跑路功能
> 
> 这个功能已经存在了，，，，
> config.php中 site title 修改为 `跑路` 即达到效果。话说跑路页面还挺好看的。

在config.php 修改了appname  修改为 `跑路` !!!怎么没有跑路页面，只提示无法访问此网站。主题模板钟也没有paolu.tpl这个文件。

**Comment by acdiost** [comment]
这个vue的管理后台，可以参考一下：https://github.com/PanJiaChen/vue-element-admin

**Comment by 40huo** [comment]
> 这个vue的管理后台，可以参考一下：https://github.com/PanJiaChen/vue-element-admin

感觉vue的几个admin后台都没有antd的好看

**Comment by tonyzzzzzz** [comment]
@40huo 那为什么不直接用antd的vue版呢

**Comment by 40huo** [comment]
> @40huo 那为什么不直接用antd的vue版呢

https://github.com/vueComponent/ant-design-vue 感觉这个挺好的，可惜不会前端

**Comment by PoetryHao** [comment]
现在更新后无法打开新的登录界面，就是直接白屏，其他界面都没问题

**Comment by 578660638** [comment]
我想问我不想要这个界面从哪里设置

**Comment by laurieryayoi** [comment]
> 我想问我不想要这个界面从哪里设置

把indexold改成index,index改成别的

**Comment by 578660638** [comment]
> > 我想问我不想要这个界面从哪里设置
> 
> 把indexold改成index,index改成别的

我好像找不到indexold 0.0

**Comment by 578660638** [comment]
为啥我这背景换了之后 他自己又换回原来的背景了

**Comment by akqzx** [comment]
加个流量图，一月、一周、一天

**Comment by ajian2002** [comment]
预置几类主题或者麻烦告知一下主题如何自己修改

**Comment by ajian2002** [comment]
商品设置有些繁琐，无法直观显示套餐内容

**Comment by laurieryayoi** [comment]
怎么改成旧版上面说了

商品设置项都是必要的，自己好好摸索一下

**Comment by perfect-network** [comment]
多个单端口多用户

**Comment by Anankke** [comment]
@perfect-network 弱智，，，

**Comment by stardock** [comment]
>  
>  

> @stardock 谁跑路一个我看看？   
载图如下，抱歉并不想把网站发出来。  
![paolu](https://user-images.githubusercontent.com/11665205/53482090-6fc43080-3ab9-11e9-9ce7-4cd14dc677e7.png)

**Comment by williamluu** [comment]
1，发现，用户收不到密码重置邮件，应该在那里修改？我已开启了邮件验证，设置了stmp，并且 可以收到注册验证邮件，但测试发现密码重置邮件收不到。
2，登录检测，弹出来错误提示，显示停留的时间太短，弹来的提示显示不明显，体验不好。来不及时就消失了。建议取消自动闪退，让用户点取消。

**Comment by Anankke** [comment]
> 1，发现，用户收不到密码重置邮件，应该在那里修改？我已开启了邮件验证，设置了stmp，并且 可以收到注册验证邮件，但测试发现密码重置邮件收不到。
> 2，登录检测，弹出来错误提示，显示停留的时间太短，弹来的提示显示不明显，体验不好。来不及时就消失了。建议取消自动闪退，让用户点取消。

自己改

**Comment by PoetryHao** [comment]
一键跑路怎么设置？

**Comment by lwsg1987** [comment]
@PoetryHao 50

**Comment by ruich97** [comment]
@lwsg1987 51

**Comment by Anankke** [comment]
@PoetryHao 70

**Comment by lwsg1987** [comment]
@Anankke 代设置完美“无法显示网页”，跟打不开那种一模一样，比一键跑路还好

**Comment by stardock** [comment]
.config.php  配置文件里面，site tile 设置为'跑路' 即可  
(真一键跑路)

**Comment by PoetryHao** [comment]
管理面板出现500错误

**Comment by Anankke** [comment]
> 管理面板出现500错误

那就别用

**Comment by myh215** [comment]
配置指南这些常用的希望做个单独的按钮，不要跟公告栏放一起。现在的操作感觉太复杂了，很难找，哪些能按哪些不能按都不是很明确。

**Comment by lwsg1987** [comment]
@myh215 有道理，但我不会写怎么办…

**Comment by laurieryayoi** [comment]
不开心了，关了

**Comment by Anankke** [comment]
揉揉，别不开心
