### ISSUE TITLE
TG机器人/ping无反应

### ISSUE THREAD

**Issue by YPandaTAT** [Anankke/ss-panel-v3-mod_Uim#496]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题
------------
使用版本为master最新版

不知道为什么/ping机器人没有反应，我按wiki里面创建了机器人，网站开启了https，并且只向@BotFather发送了 https:// 中间的域名 /auth/login，把机器人拉进群组以后/ping机器人没有反应

**Comment by laurieryayoi** [comment]
要先给机器人设置个ping命令

**Comment by YPandaTAT** [comment]
@laurieryayoi 向Botfather提交了，但是没有用
ping - 获取群组ID

**Comment by laurieryayoi** [comment]
@YPandaTAT ping - GetID

**Comment by YPandaTAT** [comment]
@laurieryayoi ping - GetID
也没反应

**Comment by YPandaTAT** [comment]
解决不了么
