### ISSUE TITLE
强迫症犯了

### ISSUE THREAD

**Issue by olperson** [Anankke/ss-panel-v3-mod_Uim#497]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

 
  关于合并订阅，演示站没有合并于是我在我的站点上配置了，在windows教程下发现点复制链接发现没有去掉?mu=0但是并不是不能用，只是文本实际显示和复制不同，在1.16日最新版本index.tpl 232行补充添加了{if !$mergeSub}?mu=0{/if}这段代码解决。

**Comment by NimaQu** [comment]
@olperson 直接 pr 上来不就行了

**Comment by olperson** [comment]
> @olperson 直接 pr 上来不就行了

我不会啊😂

**Comment by SuicidalCat** [comment]
@olperson Use Goolge and brain.

**Comment by CGDF-Github** [comment]
https://github.com/Anankke/ss-panel-v3-mod_Uim/commit/259bed97724bc89802a2e1a01a04881604460879
fixed
