### ISSUE TITLE
ie11和老版chrome卡登录界面

### ISSUE THREAD

**Issue by xiaobaoxiao** [Anankke/ss-panel-v3-mod_Uim#499]
多个机器测试了。就是个别浏览器卡登录界面。症状就是一直卡在loading的界面。请问有什么解决方案

**Comment by lenovoy450** [comment]
那就不用这些浏览器

**Comment by NimaQu** [comment]
@xiaobaoxiao 无力适配 < Chrome 60，要修自己 pr

**Comment by xiaobaoxiao** [comment]
浏览器报错。
mutation:{
SET_LOADSTATE 没识别成函数，提示缺少冒号
}

**Comment by xiaobaoxiao** [comment]
问题是用啥浏览器，我们说了不算啊。用户说了算

**Comment by Passipur** [comment]
@xiaobaoxiao 用户问就让他换浏览器呗

**Comment by xiaobaoxiao** [comment]
@Passipur 让用户换浏览器，比登天还难。。
