### ISSUE TITLE
新版界面点击登录成功后一直在跳转界面

### ISSUE THREAD

**Issue by guxyz** [Anankke/ss-panel-v3-mod_Uim#505]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

登录演示站没发现这个情况，全程参照wiki安装前端，输入账号密码后显示登录成功，然后就卡在这儿了。是否是我这儿有哪个设置不正确？

![1111](https://user-images.githubusercontent.com/46808265/51370846-65fef300-1b33-11e9-927b-133df6dded0a.png)
![22222](https://user-images.githubusercontent.com/46808265/51370851-6bf4d400-1b33-11e9-85d4-606e89c9626f.png)

**Comment by guxyz** [comment]
vue@2.5.21:6点进去，显示错误
![33333](https://user-images.githubusercontent.com/46808265/51375274-65208e00-1b40-11e9-830c-207a6ac5b648.png)

**Comment by laurieryayoi** [comment]
修了
