### ISSUE TITLE
添加优惠码时点一次会生成两个

### ISSUE THREAD

**Issue by chenyitian2004** [Anankke/ss-panel-v3-mod_Uim#520]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题（演示站521错误）

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

添加优惠码时如果优惠码空着
勾选一次性的,只在用户当次购买时有效
点击生成仅包含随机字符的优惠码
以后会自动生成两个优惠码

还有顺便问一句
hostus提供的ovz安装好docker环境的镜像
根据wiki教程安装后端的时候创建容器报错：
flag provided but not defined: --network
想问各位大佬这个怎么解决
还有我把这个参数删掉以后可以启动docker
（用的数据库对接）
网站显示已经连接上节点
但用户无法连接上节点
想知道是不是因为我修改了这个参数导致的
谢谢各位大佬

最后还想知道各位大佬的OVZ小鸡怎么安装的后端，我用wiki的一键脚本不管是WEBAPI还是数据库都连不上前端

**Comment by chenyitian2004** [comment]
还有关于高级节点体验的内容，wiki里貌似是远古版本的教程了
看得我都蒙了
请问有没有大佬能指个路告知下怎么设置

**Comment by CGDF-Github** [comment]
https://github.com/Anankke/ss-panel-v3-mod_Uim/commit/4bf5a262f1c0625643fd16bd9c4a1bfebb0ea724

fixed
