### ISSUE TITLE
crisp,geetest

### ISSUE THREAD

**Issue by MiryanSir** [Anankke/ss-panel-v3-mod_Uim#523]
测试环境PC：
qq浏览器，chrome浏览器已清空浏览器缓存
安卓手机：
qq浏览器已经清空浏览器缓存
已开启cofing中的设置，如下
/沟通设置--------------------------------------------------------------------------------------------
#客服系统设置，注册地址 https://crisp.chat/
$System_Config['enable_crisp']='ture';		//是否开启客服系统
客服id已经填写
并且已经查看了head.tpl和mian.tpl末尾确实存在调用crisp的代码但是主页还是无法显示
//验证码设置------------------------------------------------------------------------------------------

$System_Config['captcha_provider'] = 'geetest';		//取值 recaptcha | geetest(极验)
$System_Config['enable_reg_captcha'] = 'ture';		//启用注册验证码
$System_Config['enable_login_captcha'] = 'ture';	//启用登录验证码
$System_Config['enable_checkin_captcha'] = 'false';	//启用签到验证码
id和key已经填写。

**Comment by laurieryayoi** [comment]
……挂代理浏览，看看是不是JS加载不出来

**Comment by NimaQu** [comment]
瀑布图看一下

**Comment by MiryanSir** [comment]
> 瀑布图看一下


> 瀑布图看一下
commit 6d09b40b89b64c2ba24608647be9da3236b7e99b
Author: laurieryayoi <14360417+laurieryayoi@users.noreply.github.com>
Date:   Sun Dec 30 21:42:50 2018 +0800

    chenpay界面排版

diff --git a/resources/views/material/admin/payEdit.tpl b/resources/views/material/admin/payEdit.tpl
index 45d9007..a2bf410 100644
--- a/resources/views/material/admin/payEdit.tpl
+++ b/resources/views/material/admin/payEdit.tpl
@@ -37,43 +37,46 @@
 
                             <div class="form-group form-group-label">
                                 <label class="floating-label" for="number">失效通知邮箱</label>
-                                <input class="form-control" id="Notice_EMail" type="text"
+                                <input class="form-control maxwidth-edit" id="Notice_EMail" type="text"
                                        value="{$payConfig['Notice_EMail']}">
                             </div>
 
                             <div class="form-group form-group-label">
-                                <label class="floating-label" for="number">规定金额设定（不设定则无需输入，英文“|”分割，必须大于2）</label>
-                                <input class="form-control" id="Pay_Price" type="text"
+                                <label class="floating-label" for="number">规定金额设定</label>
+                                <input class="form-control maxwidth-edit" id="Pay_Price" type="text"
                                        value="{$payConfig['Pay_Price']}">
+                                <p class="form-control-guide"><i class="material-icons">info</i>不设定则无需输入，英文“|”分割，必须大于2</p>
                             </div>
 
                             <div class="form-group form-group-label">
-                                <label class="floating-label" for="amount">支付宝二维码（金额设定后需要英文“|”分割）</label>
-                                <input class="form-control" id="AliPay_QRcode" type="text"
+                                <label class="floating-label" for="amount">支付宝二维码</label>
+                                <input class="form-control maxwidth-edit" id="AliPay_QRcode" type="text"
                                        value="{$payConfig['AliPay_QRcode']}">
+                                <p class="form-control-guide"><i class="material-icons">info</i>金额设定后需要英文“|”分割</p>                                       
                             </div>
 
 
                             <div class="form-group form-group-label">
                                 <label class="floating-label" for="number">支付宝COOKIE</label>
-                                <input class="form-control" id="AliPay_Cookie" type="text"
+                                <input class="form-control maxwidth-edit" id="AliPay_Cookie" type="text"
                                        value='{$payConfig['AliPay_Cookie']}'>
                             </div>
 
                             <div class="form-group form-group-label">
                                 <label class="floating-label" for="number">微信登录地址</label>
-                                <input class="form-control" id="WxPay_Url" type="text"
+                                <input class="form-control maxwidth-edit" id="WxPay_Url" type="text"
                                        value="{$payConfig['WxPay_Url']}">
                             </div>
                             <div class="form-group form-group-label">
-                                <label class="floating-label" for="number">微信二维码（金额设定后需要英文“|”分割）</label>
-                                <input class="form-control" id="WxPay_QRcode" type="text"
+                                <label class="floating-label" for="number">微信二维码</label>
:

**Comment by MiryanSir** [comment]
我发现这个php代码没有执行，不仅crisp那个地方还有比如说客服联系方式这里
{if $config["enable_admin_contact"] == 'true'}
										<p class="card-heading">管理员联系方式</p>
										{if $config["admin_contact1"]!=null}
										<p>{$config["admin_contact1"]}</p>
										{/if}
										{if $config["admin_contact2"]!=null}
										<p>{$config["admin_contact2"]}</p>
										{/if}
										{if $config["admin_contact3"]!=null}
										<p>{$config["admin_contact3"]}</p>
										{/if}
										{/if}
已经在cofing里ture了，这里的php没有执行

**Comment by SuicidalCat** [comment]
@MiryanSir 檢查自己WEB Server配置

**Comment by MiryanSir** [comment]
网站目录下php环境已经安装了

**Comment by Zhai2333** [comment]
`ture` → `true` 😂

**Comment by MiryanSir** [comment]
> `ture` → `true`

这位同志请不要取笑我，没过6级
