### ISSUE TITLE
关于重置周期问题。

### ISSUE THREAD

**Issue by qqqgithub** [Anankke/ss-panel-v3-mod_Uim#524]
各位大佬新年好。
我已搜索过Issues，并查看了相关wiki，并没有找到和我类似的问题，才冒昧的提这个很low的问题。（也许是我眼瞎，没看到，如果哪里有请发个链接就行，先谢过！）
问题1：用户购买了季付套餐 会员有效90天 每30天重置流量为30G
请问90天、30天、30G这个值是在数据库那张表里。（或者自动任务里？）
user表里 好像没有重置周期和重置次数的值。（可能是我眼瞎，请大佬明示！）
小白一枚，大佬勿喷！
祝各位阖家欢聚，万事大吉！

**Comment by SuicidalCat** [comment]
@qqqgithub 大腦亟需升級

**Comment by laurieryayoi** [comment]
@qqqgithub 重置仅依据套餐属性，设置过重置的套餐除了下架以外不要随意动其他参数，除非你想好了

**Comment by qqqgithub** [comment]
@laurieryayoi  把套餐删除了就不会重置流量了？
如果想查当前有多少用户是90天重置 365天重置 应该怎么查？

**Comment by laurieryayoi** [comment]
@qqqgithub 只能查购买记录

**Comment by qqqgithub** [comment]
@qqqgithub 购买记录清空了。。。这玩笑开大了。
