### ISSUE TITLE
修改商品属性后，之前购买过该商品的用户使用流量不会扣减

### ISSUE THREAD

**Issue by lsbjkc** [Anankke/ss-panel-v3-mod_Uim#527]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

修改商品属性后，之前购买过该商品的用户使用流量不会扣减

commit 6d09b40b89b64c2ba24608647be9da3236b7e99b
Author: laurieryayoi <14360417+laurieryayoi@users.noreply.github.com>
Date:   Sun Dec 30 21:42:50 2018 +0800

    chenpay界面排版

diff --git a/resources/views/material/admin/payEdit.tpl b/resources/views/material/admin/payEdit.tpl
index 45d9007..a2bf410 100644
--- a/resources/views/material/admin/payEdit.tpl
+++ b/resources/views/material/admin/payEdit.tpl
@@ -37,43 +37,46 @@
 
                             <div class="form-group form-group-label">
                                 <label class="floating-label" for="number">失效通知邮箱</label>
-                                <input class="form-control" id="Notice_EMail" type="text"
+                                <input class="form-control maxwidth-edit" id="Notice_EMail" type="text"
                                        value="{$payConfig['Notice_EMail']}">
                             </div>
 
                             <div class="form-group form-group-label">
-                                <label class="floating-label" for="number">规定金额设定（不设定则无需输入
-                                <input class="form-control" id="Pay_Price" type="text"
+                                <label class="floating-label" for="number">规定金额设定</label>
+                                <input class="form-control maxwidth-edit" id="Pay_Price" type="text"
                                        value="{$payConfig['Pay_Price']}">
+                                <p class="form-control-guide"><i class="material-icons">info</i>不设定则
                             </div>
 
                             <div class="form-group form-group-label">
:

**申请添加新的特性或功能或者好的想法**

**Comment by NimaQu** [comment]
@lsbjkc 不然呢，，，

**Comment by kn007** [comment]
你买了蛋糕后，后面提价了，商家找你要差价，你不给，商家切走了你一块蛋糕？！

有这种操作吗？？？

**Comment by lsbjkc** [comment]
> @lsbjkc 不然呢，，，

还有新套餐覆盖旧套餐，用户使用流量也不扣减
