### ISSUE TITLE
最新稳定版的spay支付一直提示[非法的金额]

### ISSUE THREAD

**Issue by wxlost** [Anankke/ss-panel-v3-mod_Uim#529]
**我确认我已经阅读了** (使用 "x" 选择) - [X ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [X ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue) **我确认我做到了** (使用 "x" 选择) - [X ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [Boom ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题 **我正在申请** (使用 "x" 选择) - [X ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法  **反馈BUG** 1.请在面板路径下运行`git show HEAD`，然后贴出输出内容
commit 6d09b40b89b64c2ba24608647be9da3236b7e99b
Author: laurieryayoi <14360417+laurieryayoi@users.noreply.github.com>
Date: Sun 12月30日 21:42:50 2018 +0800 chenpay界面排版 diff --git a/resources/views/material/admin/payEdit.tpl b/resources/views/material/admin/payEdit.tpl
index 45d9007..a2bf410 100644
--- a/resources/views/material/admin/payEdit.tpl
+++ b/resources/views/material/admin/payEdit.tpl
@@ -37,43 +37,46 @@ <div class="form-group form-group-label"> <label class="floating-label" for="number">失效通知邮箱</label>
- <input class="form-control" id="Notice_EMail" type="text"
+ <input class="form-control maxwidth-edit" id="Notice_EMail" type="text" value="{$payConfig['Notice_EMail']}"> </div> <div class="form-group form-group-label">
- <label class="floating-label" for="number">规定金额设定（不设定则无需输入，英文“|”分割，必须大于2）</la
- <input class="form-control" id="Pay_Price" type="text"
+ <label class="floating-label" for="number">规定金额设定</label>
+ <input class="form-control maxwidth-edit" id="Pay_Price" type="text" value="{$payConfig['Pay_Price']}">
+ <p class="form-control-guide"><i class="material-icons">info</i>不设定则无需输入，英文“|”分割，必须大于 </div> <div class="form-group form-group-label">
- <label class="floating-label" for="amount">支付宝二维码（金额设定后需要英文“|”分割）</label>
- <input class="form-control" id="AliPay_QRcode" type="text"
+ <label class="floating-label" for="amount">支付宝二维码</label>
+ <input class="form-control maxwidth-edit" id="AliPay_QRcode" type="text" value="{$payConfig['AliPay_QRcode']}">
+ <p class="form-control-guide"><i class="material-icons">info</i>金额设定后需要英文“|”分割</p> </div> <div class="form-group form-group-label"> <label class="floating-label" for="number">支付宝COOKIE</label>
- <input class="form-control" id="AliPay_Cookie" type="text"
+ <input class="form-control maxwidth-edit" id="AliPay_Cookie" type="text" value='{$payConfig['AliPay_Cookie']}'> </div> <div class="form-group form-group-label"> <label class="floating-label" for="number">微信登录地址</label>
- <input class="form-control" id="WxPay_Url" type="text"
+ <input class="form-control maxwidth-edit" id="WxPay_Url" type="text" value="{$payConfig['WxPay_Url']}"> </div> <div class="form-group form-group-label">
- <label class="floating-label" for="number">微信二维码（金额设定后需要英文“|”分割）</label>
- <input class="form-control" id="WxPay_QRcode" type="text"
+ <label class="floating-label" for="number">微信二维码</label>
+ <input class="form-control maxwidth-edit" id="WxPay_QRcode" type="text" value="{$payConfig['WxPay_QRcode']}">
+ <p class="form-control-guide"><i class="material-icons">info</i>金额设定后需要英文“|”分割</p> </div> <div class="form-group form-group-label"> <label class="floating-label" for="number">微信COOKIE</label>
- <input class="form-control" id="WxPay_Cookie" type="text"
+ <input class="form-control maxwidth-edit" id="WxPay_Cookie" type="text" value="{$payConfig['WxPay_Cookie']}"> </div> (END)
2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容 

VM186:109 GM_ValueInfo: (2) ["CatPW", "CatPW_Manage"] {StorageSave: true, UpdataConfig: {…}, StorageExp: 365} {date: "2019/2/5", sCode: "", unPW: "", Src: "https://pan.baidu.com/s/11Ex4O87-_dJr7AyGnkqoYw", surl: "", …}
VM186:164 版本号信息异常
UpdataPlugin @ VM186:164
init @ VM186:168
(anonymous) @ VM186:171
(anonymous) @ VM186:1112
(anonymous) @ VM186:1113
value @ VM186:1
(anonymous) @ VM175:1
(anonymous) @ VM175:1
value @ VM175:1
(anonymous) @ VM186:1
(anonymous) @ VM186:1
i @ injected.js:1
Inject @ injected.js:1
$ @ injected.js:1
(anonymous) @ injected.js:1
(anonymous) @ VM175:1
(anonymous) @ VM175:1
j @ VM175:1
O @ VM175:1
setTimeout (async)
LoadScripts.c.a.load @ VM175:1
Promise.then (async)
(anonymous) @ VM175:1
DevTools failed to parse SourceMap: https://.ru/user/jquery.min.map
code:219 将要使用 SPay 方法充值NaN元
jquery@3.2.1:4 POST https://.ru/user/payment/purchase 500
send @ jquery@3.2.1:4
ajax @ jquery@3.2.1:4
(anonymous) @ code:226
dispatch @ jquery@3.2.1:3
q.handle @ jquery@3.2.1:3
trigger @ jquery@3.2.1:4
(anonymous) @ jquery@3.2.1:4
each @ jquery@3.2.1:2
each @ jquery@3.2.1:2
trigger @ jquery@3.2.1:4
(anonymous) @ base.min.js:1
e @ jquery@3.2.1:3
handle @ base.min.js:1
dispatch @ jquery@3.2.1:3
q.handle @ jquery@3.2.1:3
trigger @ jquery@3.2.1:4
(anonymous) @ jquery@3.2.1:4
each @ jquery@3.2.1:2
each @ jquery@3.2.1:2
trigger @ jquery@3.2.1:4
e @ base.min.js:1
setTimeout (async)
a.fn.emulateTransitionEnd @ base.min.js:1
(anonymous) @ base.min.js:1
e @ jquery@3.2.1:3
handle @ base.min.js:1
dispatch @ jquery@3.2.1:3
q.handle @ jquery@3.2.1:3
trigger @ jquery@3.2.1:4
(anonymous) @ jquery@3.2.1:4
each @ jquery@3.2.1:2
each @ jquery@3.2.1:2
trigger @ jquery@3.2.1:4
e @ base.min.js:1
setTimeout (async)
a.fn.emulateTransitionEnd @ base.min.js:1
c.backdrop @ base.min.js:1
c.show @ base.min.js:1
(anonymous) @ base.min.js:1
each @ jquery@3.2.1:2
each @ jquery@3.2.1:2
b @ base.min.js:1
(anonymous) @ code:224
dispatch @ jquery@3.2.1:3
q.handle @ jquery@3.2.1:3
 **申请添加新的特性或功能或者好的想法** 

启用spay支付功能,然后输入任意金额都是提示[非法的金额],F12调试输出显示NaN,就好像金额输入框的内容没有被提交一样.

$System_Config['amount']=[2,23,233,2333,23333];		//充值金额选项设定

**Comment by laurieryayoi** [comment]
fixed
