### ISSUE TITLE
在线设备数限制不起效

### ISSUE THREAD

**Issue by mondayfri** [Anankke/ss-panel-v3-mod_Uim#541]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [x ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

**申请添加新的特性或功能或者好的想法**
---------------------------->

在线设备数限制在2个，但可以随意登陆多个，研究许久但没有结果，T-T，如图 https://i.loli.net/2019/02/17/5c695387761a2.jpg

**Comment by NimaQu** [comment]
@mondayfri 根据 ip 限制

**Comment by perfect-network** [comment]
+1这是根据IP限制的，😂
