### ISSUE TITLE
关于用户使用流量上传时间间隔的建议

### ISSUE THREAD

**Issue by yangyzp** [Anankke/ss-panel-v3-mod_Uim#547]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**
https://ww1.sinaimg.cn/large/005BYqpgly1g0bqr1bufdj310l0c2glz.jpg
如上图，用户使用的流量每1分钟就会上传一次，时间似乎有点太短了，对于数据库配置不是很好的机器，用户稍多一点，特别是晚上，数据库就容易爆炸。。
能否设置修改这个上传使用流量的时间间隔

**Comment by galaxychuck** [comment]
@yangyzp 加錢

**Comment by lenovoy450** [comment]
你是有114514个节点，1145141919810个用户吗？
做人不要太葛朗台了。

**Comment by rico93** [comment]
@yangyzp 50解忧愁

**Comment by yangyzp** [comment]
@lenovoy450  提供建议而已，刚搬家的~~ 之前是1G的

**Comment by yangyzp** [comment]
@rico93  怎么联系？

**Comment by rico93** [comment]
@yangyzp tg @ricobb
