### ISSUE TITLE
中转链路表的问题

### ISSUE THREAD

**Issue by Colinwood11** [Anankke/ss-panel-v3-mod_Uim#557]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [X] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [X] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

关于中转的
1.设置中转后链路表不显示

2.使用内网中转时第三个内网无效，具体请看

节点：A B C D
用中转规则设置，A---内网-->B    正常使用
但是当    B---内网-->C    设置后马上连接能正常转至C，可是一会儿过后再连接
B后端报错，显示
 invalid hostname: C节点外网IP,内网#B节点ID when resolve DNS

但奇怪的是
如果将 B--无内网-->D
能正常使用

其实我也不确定是后端的问题还是前端的问题，由于在旧版本SSPANEL-V3-MOD测试后可以正常使用，所以在反馈issues就写上了这个

**申请添加新的特性或功能或者好的想法**

**Comment by Anankke** [comment]
emmm换过后端吗？

**Comment by Colinwood11** [comment]
> emmm换过后端吗？

我有觉得是后端的锅
测试问题1时，后端使用的是WIKI中的安装。
问题1与2在releases  v2.2.0的版本中是完全可以正常使用的
所以我就到这发Issues了

**Comment by CGDF-Github** [comment]
https://github.com/Anankke/ss-panel-v3-mod_Uim/commit/abe8359ecb9327d7e0697ef26d721dc3d8ee0293

已修复，请升级后，**重新**编辑并保存节点

**Comment by Colinwood11** [comment]
> [abe8359](https://github.com/Anankke/ss-panel-v3-mod_Uim/commit/abe8359ecb9327d7e0697ef26d721dc3d8ee0293)
> 
> 已修复，请升级后，**重新**编辑并保存节点

我还有个问题，现在的规则是节点不显示  就无法连接嘛？  我需要怎么改  能不能麻烦告知

**Comment by CGDF-Github** [comment]
> > [abe8359](https://github.com/Anankke/ss-panel-v3-mod_Uim/commit/abe8359ecb9327d7e0697ef26d721dc3d8ee0293)
> > 已修复，请升级后，**重新**编辑并保存节点
> 
> 我还有个问题，现在的规则是节点不显示 就无法连接嘛？ 我只是单纯的想隐藏需要怎么改 能不能麻烦告知

节点不显示是因为等级不够还是节点分组不为0？还是bug？

**Comment by CGDF-Github** [comment]
> > [abe8359](https://github.com/Anankke/ss-panel-v3-mod_Uim/commit/abe8359ecb9327d7e0697ef26d721dc3d8ee0293)
> > 已修复，请升级后，**重新**编辑并保存节点
> 
> 我还有个问题，现在的规则是节点不显示 就无法连接嘛？ 我只是单纯的想隐藏需要怎么改 能不能麻烦告知

哦我理解错了，请忽视上一条回复

**Comment by CGDF-Github** [comment]
现在的规则应该依然和之前相同，你升级之后依然会出现这个问题吗？

**Comment by Colinwood11** [comment]
> 现在的规则应该依然和之前相同，你升级之后依然会出现这个问题吗？

更新后OK了，但是链路表那边也还是有问题。  不显示

**Comment by Colinwood11** [comment]
> 现在的规则应该依然和之前相同，你升级之后依然会出现这个问题吗？

OK了 但是链路表一样不显示

**Comment by CGDF-Github** [comment]
@Colinwood11 难道以前链路表显示？？？

**Comment by Colinwood11** [comment]
> 以前链路表

以前链路表不显示的么？？？？？？？？？

**Comment by CGDF-Github** [comment]
@Colinwood11 你说的是用户可以看到的那个链路表？要不你版本降级一下看看？

**Comment by Colinwood11** [comment]
> @Colinwood11 你说的是用户可以看到的那个链路表？要不你版本降级一下看看？

EMM  并不是有那个需求，只是顺便这么一提，主要内网解决了就OK，如果需要帮忙测试请叫我。话说我没在Commint里有看到这次的修复信息，是不是已经清除了？

**Comment by CGDF-Github** [comment]
否

**Comment by Colinwood11** [comment]
> 否

总之谢谢大佬！
