### ISSUE TITLE
求Meterial Design风格的设计

### ISSUE THREAD

**Issue by Mainvooid** [Anankke/ss-panel-v3-mod_Uim#560]
**我正在申请**  (使用 "x" 选择)
- [x ] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**

话说演示站的首页还没有原先魔改版的扁平化粉蓝色好看，没有前端重新设计一下Meterial Design风格的页面么？

**Comment by laurieryayoi** [comment]
indexold还在你可以自己改回去
