### ISSUE TITLE
来自✈️奸商的想法，多个不同端口的单端口多用户配置

### ISSUE THREAD

**Issue by heyuan0028** [Anankke/ss-panel-v3-mod_Uim#562]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

目前很多优秀线路的鸡鸡都挺贵的，（TW HK商宽，家宽）所以NAT小鸡因为价格便宜成为了大多数人的选择，但是目前ss-panel-v3-mod单端口多用户只能指定一个端口来添加节点，因为NAT小鸡有些商家分配端口是随机的，所以很难统一一个端口来添加节点。
这几天搜寻谷歌N次，都没有找到多个不同端口单端口多用户节点的类似信息。
所以这个想法是否可行？

**Comment by lenovoy450** [comment]
你可以使用65535个单端口.

**Comment by JohnFreeman9** [comment]
@lenovoy450 甚至可以在65535个端口上实现复用，达到∞后端同时使用，因(0, ∞)中包含11 4 5 14这几个自然数，所以该方法极其恶臭，QED

**Comment by heyuan0028** [comment]
> @lenovoy450 甚至可以在65535个端口上实现复用，达到∞后端同时使用，因(0, ∞)中包含11 4 5 14这几个自然数，所以该方法极其恶臭，QED

单端口多用户节点都是基于一个单端口多用户的承载用户和一个承载节点，用户和节点信息都制定了一个端口，比如65535，那么在添加单端口多用户节点后，端口会被自动指定为65535，如果我有一个NAT小鸡端口是23333，我再添加一个2333的单端口承载用户和承载节点，那么我添加这个单端口多用户节点后，它如何判定端口号？

**Comment by yry0008** [comment]
@heyuan0028 端口偏移了解一下
去看一下端口偏移分支

**Comment by yry0008** [comment]
后端要跟着转发。docker的转发规则：我原来单端口21082，现在我要用其他端口(例如8080)，于是就
`docker run -p 8080:21082 <old commands> `
注意一下 --network=host 要删掉
关于脚本的版本：用iptable进行转发

**Comment by heyuan0028** [comment]
> 后端要跟着转发。docker的转发规则：我原来单端口21082，现在我要用其他端口(例如8080)，于是就
> `docker run -p 8080:21082 <old commands> `
> 注意一下 --network=host 要删掉
> 关于脚本的版本：用iptable进行转发

但是如果我通过原来的单端口，无法连接上NAT小鸡？

**Comment by yry0008** [comment]
转发了之后当然要用新的端口链接啦……

**Comment by wulimaxjjj** [comment]
我对这个也有疑问，用master。我有两个节点，节点1和节点2，我要让节点1只用单端口多用户，用443端口；节点2只用单端口多用户，用端口8080，现在是不是不能实现？求教

**Comment by lwsg1987** [comment]
@wulimaxjjj 可以

**Comment by wulimaxjjj** [comment]
怎么搞定求教！

**Comment by JusufUs** [comment]
> 我对这个也有疑问，用master。我有两个节点，节点1和节点2，我要让节点1只用单端口多用户，用443端口；节点2只用单端口多用户，用端口8080，现在是不是不能实现？求教

求教 @lwsg1987

**Comment by JusufUs** [comment]
> @heyuan0028 端口偏移了解一下
> 去看一下端口偏移分支
@yry0008 大神所说的偏移，应该是得让所有用户的端口统一后才可以吧
