### ISSUE TITLE
用户中心打开节点页面报错

### ISSUE THREAD

**Issue by baiyou2014** [Anankke/ss-panel-v3-mod_Uim#565]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**
如图所示
[img]https://s2.ax1x.com/2019/03/02/kqEewd.png[/img]

Whoops \ Exception \ ErrorException (E_WARNING)
Creating default object from empty value

Open: /www/wwwroot/lu/app/Controllers/UserController.php
 
    public function node($request, $response, $args)
    {
        $user = Auth::getUser();
        $nodes = Node::where('type', 1)->orderBy('node_class')->orderBy('name')->get();
        $relay_rules = Relay::where('user_id', $this->user->id)->orwhere('user_id', 0)->orderBy('id', 'asc')->get();
        if (!Tools::is_protocol_relay($user)) {
            $relay_rules = array();
        }
 
        $array_nodes=array();
        $nodes_muport = array();
 
        foreach($nodes as $node){
            if($node->node_group!=$user->node_group && $node->node_group!=0){
                continue;
            }
            if ($node->sort == 9) {
                $mu_user = User::where('port', '=', $node->server)->first();
                $mu_user->obfs_param = $this->user->getMuMd5();
                array_push($nodes_muport, array('server' => $node, 'user' => $mu_user));
                continue;
            }
            $array_node=array();
 
            $array_node['id']=$node->id;
            $array_node['class']=$node->node_class;
            $array_node['name']=$node->name;
            $array_node['server']=$node->server;
            $array_node['sort']=$node->sort;
            $array_node['info']=$node->info;
            $array_node['mu_only']=$node->mu_only;
            $array_node['group']=$node->node_group;
 
            $array_node['raw_node'] = $node;
            $regex = Config::get('flag_regex');
            $matches = array();
            preg_match($regex, $node->name, $matches);
            if (isset($matches[0])) {
                $array_node['flag'] = $matches[0].'.png';

**Comment by pang-w** [comment]
$mu_user = User::where('port', '=', $node->server)->first();

同样遇到这个问题， 为什么端口号要等于节点服务器呢？ @NimaQu
