### ISSUE TITLE
SPay充值时停留在连接支付网关对话框

### ISSUE THREAD

**Issue by gdasoul** [Anankke/ss-panel-v3-mod_Uim#570]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

使用SPay支付方式时，点击充值后会一直停留在正在连接支付网关对话框，之后就没有反应了。

![image](https://user-images.githubusercontent.com/23315230/54031658-54100700-41ea-11e9-9682-fefee10249c4.png)

**Comment by wxlost** [comment]
是的...开始是金额错误..大佬修复了..然后就卡这里了..无奈

**Comment by laurieryayoi** [comment]
spay tony没写完，别用了(

**Comment by NimaQu** [comment]
@laurieryayoi 建议抵制 TonyPay 逼 Tony 写完 spay

**Comment by tonyzzzzzz** [comment]
@NimaQu 滚

**Comment by CGDF-Github** [comment]
Tony垄断企业打压友商实锤了！

**Comment by NimaQu** [comment]
@CGDF-Github 实锤实锤，立即全网封杀

**Comment by wxlost** [comment]
大佬修一修吧

**Comment by 867342200** [comment]
我用过很多版本的sspanel，有很多版本都存在这样一个问题：账户已过期，请续费后使用
不知道为什么，账号设置成普通之后，就有这个提示，不知道是为什么

**Comment by Anankke** [comment]
> 我用过很多版本的sspanel，有很多版本都存在这样一个问题：账户已过期，请续费后使用
> 不知道为什么，账号设置成普通之后，就有这个提示，不知道是为什么

跟 Spay 这个 issue 有什么关系吗？

Issue 是你瞎问问题的地方吗？

已 ban

PS：这个 Issue 已修复。
