### ISSUE TITLE
用户添订阅和二维码添加节点不能ping通也无法使用

### ISSUE THREAD

**Issue by MaleiSiyin** [Anankke/ss-panel-v3-mod_Uim#571]
安装配置正常 节点数据库对接成功。
唯一问题；用户添订阅和二维码添加节点不能ping通也无法使用
`https://s2.ax1x.com/2019/03/11/APkLsH.png`

**Comment by lwsg1987** [comment]
@MaleiSiyin 防火墙关了吗
