### ISSUE TITLE
请问中转规则是不是不能用于单端口多用户

### ISSUE THREAD

**Issue by lsbjkc** [Anankke/ss-panel-v3-mod_Uim#575]
我的节点全部用的单端口，尝试设置好中转规则，可是实测并没有中转效果，节点仍然是直连，没办法转发流量到指定的目的地节点/(ㄒoㄒ)/~~

**Comment by NimaQu** [comment]
@lsbjkc 在我印象中协议式单端口多用户不能中转

**Comment by lsbjkc** [comment]
> @lsbjkc 在我印象中协议式单端口多用户不能中转

我想用SSR的重定向功能来做中转，可是userapi里面找不到设置的地方，userconfig里面设置了也不起作用

**Comment by laurieryayoi** [comment]
@lsbjkc 重定向是非SSR连接访问的时候生效的，你怎么设置都没用
