### ISSUE TITLE
添加统计代码的问题

### ISSUE THREAD

**Issue by zwx1231** [Anankke/ss-panel-v3-mod_Uim#576]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**
.config 文件中开启
$System_Config['enable_analytics_code']= 'true';

然后在指定目录创建了analytics.tpl ，并在里面粘贴了Google提供的完整统计代码。

之后访问网站报错500。

debug模式报错代码：
SmartyCompilerException thrown with message "Syntax error in template "file:/www/wwwroot/ladder/resources/views/material/analytics.tpl"  on line 5 "function gtag(){dataLayer.push(arguments);}"  - Unexpected ".", expected one of: "}""

想问一下为什么会这样，谢谢作者！

**申请添加新的特性或功能或者好的想法**

**Comment by zwx1231** [comment]
已解决!

问题原因:
css和js的{}与smarty定界符冲突

解决办法:
把js的代码用literal包起来
function gtag(){dataLayer.push(arguments);}
将这一行用
<literal>

</literal>


.config参数有写这一办法，，，是我不懂前端，把这两个写在了最前和最后。。。

**Comment by nick1325** [comment]
> 已解决!
> 
> 问题原因:
> css和js的{}与smarty定界符冲突
> 
> 解决办法:
> 把js的代码用literal包起来
> function gtag(){dataLayer.push(arguments);}
> 将这一行用
> .config参数有写这一办法，，，是我不懂前端，把这两个写在了最前和最后。。。

你好大佬，能分享如何写这个吗，我贴google analytics代码到analytics.tpl，网站500 error。
