### ISSUE TITLE
发现一个XSS漏洞

### ISSUE THREAD

**Issue by gouduyao** [Anankke/ss-panel-v3-mod_Uim#579]
在个人资料修改页面，修改联系方式那里，可以插入XSS代码
![image](https://user-images.githubusercontent.com/48701703/54574904-1b173400-4a2d-11e9-81c6-9eae2cf76a45.png)
![image](https://user-images.githubusercontent.com/48701703/54575024-8eb94100-4a2d-11e9-9c32-7f18cd90f2f5.png)

**Comment by Anankke** [comment]
实际有过滤，非存储型 XSS，请自行检查数据库相关键值确认。
