### ISSUE TITLE
在用户列表里面搜索用户的时候，反应速度太慢，才30多个用户

### ISSUE THREAD

**Issue by zhenlinhgs** [Anankke/ss-panel-v3-mod_Uim#580]
新面板，买的2H4G小鸡AWS日本，才30个用户，在用户列表里面搜索用户的时候，账号填进去搜索，没有马上显示出搜索结果，会延迟个1-2秒，才显示出来搜索结果，感觉这个用户列表的搜索速度比之前的面板慢了好多（之前面板都是账号填进去搜索结果就马上显示出来了，基本上没延迟，这个新面板延迟挺厉害的，不知道是不是面板问题），求大佬解答

**Comment by laurieryayoi** [comment]
@zhenlinhgs 应该就你一个人这样

**Comment by zhenlinhgs** [comment]
那我这个是什么问题呢？是小鸡问题，还是面板问题呢?

**Comment by laurieryayoi** [comment]
@zhenlinhgs 反正不是面板问题

**Comment by zhenlinhgs** [comment]
> @zhenlinhgs 反正不是面板问题
哦，我一开始也认为我自己搭建的有问题，然后我有重新搭建了个全新的面板，然后添加了10多个用户之后，自己再去搜索用户，结果还是一样，用户名填进去搜索，搜索的结果没有马上显示，而是一样会延迟个1-2秒，才显示出来

**Comment by laurieryayoi** [comment]
![img](https://puu.sh/D36Fr/b018f3b127.gif)

**Comment by zhenlinhgs** [comment]
> @zhenlinhgs反正不是面板问题




> @zhenlinhgs反正不是面板问题

![111111](https://user-images.githubusercontent.com/36321109/54740142-76941e00-4bf5-11e9-9866-b6fe630a2d53.gif)

**Comment by zhenlinhgs** [comment]
> @zhenlinhgs应该就你一个人这样

第一次弄GIF有点不懂，慢了些不好意思

**Comment by laurieryayoi** [comment]
@zhenlinhgs 不就是这个速度吗，你还想怎么快……，还是说你想要以前的用户一多就要加载个十几秒才能加载出来的？

**Comment by zhenlinhgs** [comment]
不是，用户列表加载慢的问题，是搜索用户的时候，搜索出来的用户显示的结果有点慢和延迟

**Comment by zhenlinhgs** [comment]
![2222](https://user-images.githubusercontent.com/36321109/54740551-b4457680-4bf6-11e9-9a0b-a083bab444da.gif)

**Comment by NimaQu** [comment]
@zhenlinhgs 建议换电脑

**Comment by zhenlinhgs** [comment]
你看看这2个动图，一个搜索用户的速度是账号输入进去结果就出来了，一个是账号输进去，结果还要等一会才会显示结果

**Comment by zhenlinhgs** [comment]
这两个动图是用同一个电脑录的

**Comment by laurieryayoi** [comment]
@zhenlinhgs 现在这个和以前的实现不同，以前数据都是一次性给，但是你修改完用户应该是每次都回到第一页的，很麻烦，现在应该是每次都请求数据

**Comment by zhenlinhgs** [comment]
哦，那这样的话，后面人数多了，要是每次都请求数据的话，速度会不会更慢？，还是说他的速度就是这样子，不管人数多还是少，都是每次请求数据这个固定的速度的

**Comment by laurieryayoi** [comment]
> 哦，那这样的话，后面人数多了，要是每次都请求数据的话，速度会不会更慢？，还是说他的速度就是这样子，不管人数多还是少，都是每次请求数据这个固定的速度的

现在无论用户多少都是这个速度

**Comment by zhenlinhgs** [comment]
哦，那还好，

**Comment by zhenlinhgs** [comment]
还有一个问题，就是直接搜索链接密码的话，搜索不出账户来，要端口或者是用户名才能搜索

**Comment by zhenlinhgs** [comment]
直接搜索用户的        连接密码         的话，搜索不出账户来，要端口或者是用户名才能搜索，这样是不是省了一定的搜索时间了

**Comment by laurieryayoi** [comment]
@zhenlinhgs 不支持某些字段的检索

**Comment by zhenlinhgs** [comment]
哦，原来啊，非常感谢大佬的回复
