### ISSUE TITLE
各位大佬，麻烦看下我下面的这个截图

### ISSUE THREAD

**Issue by zhenlinhgs** [Anankke/ss-panel-v3-mod_Uim#582]
不知道为什么，我就有个每天都重启一次服务器的习惯，然后今天忽然发现，我的网站目录的“所有者”全部自己变成WWW了，然后权限全部都变成755了，这个是怎么回事
![`DUN0XL {})Q32OF$Z388X](https://user-images.githubusercontent.com/36321109/54829414-5053a880-4cf1-11e9-868a-83d0112f144d.png)
还有就是变成这样的话，会不会有什么影响？如果要恢复的话，我要怎么恢复会原来的“所有者”root去，因为一个一个修改好要命啊

**Comment by WooMai** [comment]
。。。。
