### ISSUE TITLE
用国内商家发信遇到的问题

### ISSUE THREAD

**Issue by qws910123** [Anankke/ss-panel-v3-mod_Uim#583]
**我确认我已经阅读了** (使用 "x" 选择)

- [X ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ X] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ X] 申请添加新的特性或功能或者好的想法

**反馈BUG**
使用smtp发信，对于国内某些商家设置了发信间隔检测。
短时间大量发信会填写验证码，或者直接进草稿箱。
能否添加队列异步发信

**Comment by Anankke** [comment]
pr welcome

**Comment by Anankke** [comment]
建议考虑更换发信服务商或者自建邮件服务解决。
