### ISSUE TITLE
后端内存占用过高

### ISSUE THREAD

**Issue by lsbjkc** [Anankke/ss-panel-v3-mod_Uim#584]
ssr后端内存占用会越来越高
![image](https://user-images.githubusercontent.com/43370337/54875754-75eec800-4e3f-11e9-9ade-87eb1e51d58a.png)
大概三天左右，几乎要把1G内存都占满了
![image](https://user-images.githubusercontent.com/43370337/54875759-8acb5b80-4e3f-11e9-8c0a-d22495e51efc.png)

**Comment by NimaQu** [comment]
@lsbjkc 重写，请

**Comment by laurieryayoi** [comment]
@lsbjkc 这是面板issue啊，又不是后端

**Comment by lenovoy450** [comment]
16G起步
