### ISSUE TITLE
求修复用户列表界面无法根据流量排序

### ISSUE THREAD

**Issue by lsc272** [Anankke/ss-panel-v3-mod_Uim#585]
这个问题实在太难受了……版主希望不要说爱升不升这种话了，毕竟我们也是爱好者，实在不行付费解决也行。

**我确认我已经阅读了** (使用 "x" 选择)

- [X ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [X ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [X ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [X ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [X ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

**Comment by laurieryayoi** [comment]
@lsc272 无解，要么打开列表卡几十秒，要么不能排

**Comment by WooMai** [comment]
@laurieryayoi 其实可以config里面加个选项，自由选择（

**Comment by laurieryayoi** [comment]
你可以自己去phpmyadmin排
last day t这个

**Comment by Anankke** [comment]
其实根本不会卡几十秒
能卡几十秒的基本上都是性能不好
优化做的好的话 8k 用户一般可以在 15 秒内打开
是完全可以接受的
所以我也支持恢复这个功能
或者在 conf 里面加入相关选项

**Comment by CGDF-Github** [comment]
unlocked
