### ISSUE TITLE
yftpay适配浏览器问题

### ISSUE THREAD

**Issue by lhongtao666** [Anankke/ss-panel-v3-mod_Uim#589]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

yftpay在手机qq浏览器 Safari等浏览器可以使用 但在Edge手机客户端会卡在Code/yft页面然后返回404 在微信内置浏览器的话则会直接显示参数出错，请检查是否缺失必要参数！

**Comment by Anankke** [comment]
不缺
