### ISSUE TITLE
工单问题

### ISSUE THREAD

**Issue by majie88881234** [Anankke/ss-panel-v3-mod_Uim#590]
提交工单以后应该自动返回到工单列表，目前版本提交以后停留在工单窗口！

**Comment by mxihan** [comment]
@majie88881234 可为什么我觉得停留在工单窗口的交互更好呢？可以很方便的让顾客和客服确认工单是否提交成功

**Comment by majie88881234** [comment]
返回到工单列表如果有了工单不就是提交成功了吗？

**Comment by laurieryayoi** [comment]
多个回复的时候比较清楚
