### ISSUE TITLE
有没有大佬做个节点排序功能。后面的节点都没人。。。

### ISSUE THREAD

**Issue by JusufUs** [Anankke/ss-panel-v3-mod_Uim#592]
有没有大佬做个节点排序功能。前面几个节点都炸了，然而后面的节点都没人。。。
比如说推荐节点，让订阅的时候排序到前面，这样管理员可以根据人数控制排序。
都挤到前几个节点，我看别人机场也都是这样，好像选前几个是通病

**Comment by lwsg1987** [comment]
@JusufUs 难度有点大

**Comment by JusufUs** [comment]
@lwsg1987 大佬大佬。pr welcome

**Comment by zhaokaixs** [comment]
这玩意做运营，，会不会被喝茶

**Comment by laurieryayoi** [comment]
> 这玩意做运营，，会不会被喝茶

会

**Comment by tonyzzzzzz** [comment]
@zhaokaixs 您好，我们和北京公安局联网的哦亲亲

**Comment by akqzx** [comment]
> > 这玩意做运营，，会不会被喝茶
> 
> 会

不收钱的呢？嘿嘿

**Comment by tonyzzzzzz** [comment]
@akqzx 您好，也会被公安局记录在案的呢亲亲

**Comment by Anankke** [comment]
> 这玩意做运营，，会不会被喝茶

此地不版聊，请尊重 103 个 Watchers
