### ISSUE TITLE
管理面板边栏在手机端无法点出来

### ISSUE THREAD

**Issue by PoetryHao** [Anankke/ss-panel-v3-mod_Uim#595]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

管理面板的边栏菜单在手机端无法点出来

**Comment by PoetryHao** [comment]
主要问题是手机边栏无法显示，
git show head 输出内容为：
commit 6e7a04f3967bbd9617e650c5a74aa0124b0e4df0
Author: laurieryayoi <14360417+laurieryayoi@users.noreplDate:   Sun Feb 24 16:26:06 2019 +0800

    修复合并订阅时windows点击复制链接

diff --git a/resources/views/material/user/index.tpl b/rindex 35e74f8..a2b7d89 100644
--- a/resources/views/material/user/index.tpl
+++ b/resources/views/material/user/index.tpl

**Comment by LifeVictory** [comment]
最新dev 安装后错误500  其他分支正常
