### ISSUE TITLE
更新版本之后出现500

### ISSUE THREAD

**Issue by akqzx** [Anankke/ss-panel-v3-mod_Uim#603]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

`commit 6e7a04f3967bbd9617e650c5a74aa0124b0e4df0
Author: laurieryayoi <14360417+laurieryayoi@users.noreply.github.com>
Date:   Sun Feb 24 16:26:06 2019 +0800

    修复合并订阅时windows点击复制链接

diff --git a/resources/views/material/user/index.tpl b/resources/views/material/user/index.tpl
index 35e74f8..a2b7d89 100644
--- a/resources/views/material/user/index.tpl
+++ b/resources/views/material/user/index.tpl
@@ -227,7 +227,7 @@
`

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

页面500
Open: /www/wwwroot/ss.xxxx.vip/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php
    /**
     * Get Id
     *
     * @param string $input
     *
     * @return bool|string
     */
    public function getId($input)
    {
        if (preg_match('~^([\'"]*)([0-9]*[a-zA-Z_]\w*)\1$~', $input, $match)) {
            return $match[ 2 ];
        }
        return false;
    }
 
    /**
     * Get variable name from string
     *
     * @param string $input
     *
     * @return bool|string
     */
    public function getVariableName($input)
    {
        if (preg_match('~^[$]_smarty_tpl->tpl_vars\[[\'"]*([0-9]*[a-zA-Z_]\w*)[\'"]*\]->value$~', $input, $match)) {
            return $match[ 1 ];
        }
        return false;
    }
 
    /**
     * Set nocache flag in variable or create new variable
     *
     * @param string $varName
     */
    public function setNocacheInVariable($varName)
    {
        // create nocache var to make it know for further compiling
        if ($_var = $this->getId($varName)) {
            if (isset($this->template->tpl_vars[ $_var ])) {

在/user/panel 页面点击管理中心出现500
另外在后台用户列表点击切换用户也出现500，麻烦大佬指点一下~万分感谢

**申请添加新的特性或功能或者好的想法**

**Comment by laurieryayoi** [comment]
php xcat update

**Comment by akqzx** [comment]
> php xcat update

已经操作过升级了哦，问题依旧，所以来问问。

`[root@localhost ss.xxxx.vip]# php xcat update
备份成功

开始升级ssrdownload...
From https://github.com/xcxnig/ssr-download
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
升级ssrdownload结束
开始升级QQWry...
downloading....finish....升级QQWry结束


新增配置项通常带有默认值，因此通常即使不作任何改动网站也可以正常运行
以下是迁移附注：

迁移完成

开始升级composer依赖...
You are already using composer version 1.8.4 (stable channel).
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
升级composer依赖结束，请自行根据上方输出确认是否升级成功
You have mail in /var/spool/mail/root
`

**Comment by laurieryayoi** [comment]
自己看下合并订阅链接这项设置了没

**Comment by akqzx** [comment]
[root@localhost config]# cat .config.php |grep mergeSub
$System_Config['mergeSub'] = 'false';						//合并订阅设置 可选项 false / true
[root@localhost config]# 

已经设置为false的

**Comment by akqzx** [comment]
发现执行php xcat update有提示Warning，不知道是否有关系
[root@localhost ss.xxxx.vip]# php xcat update
备份成功

开始升级ssrdownload...
From https://github.com/xcxnig/ssr-download
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
升级ssrdownload结束
开始升级QQWry...
downloading....finish....升级QQWry结束


新增配置项通常带有默认值，因此通常即使不作任何改动网站也可以正常运行
以下是迁移附注：

迁移完成

开始升级composer依赖...
You are already using composer version 1.8.4 (stable channel).
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
升级composer依赖结束，请自行根据上方输出确认是否升级成功
You have mail in /var/spool/mail/root

**Comment by akqzx** [comment]
我对比了我服务器上的composer.json、composer.lock，和github上的文件内容是一致的。。。
