### ISSUE TITLE
Telegram OAuth 配置成功但是无法绑定站点

### ISSUE THREAD

**Issue by qws910123** [Anankke/ss-panel-v3-mod_Uim#610]
**我确认我已经阅读了** (使用 "x" 选择)

- [ X] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [X ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题
![22222](https://user-images.githubusercontent.com/48037467/56077113-e4092800-5e0a-11e9-8611-ad0cbbdca213.png)
![11111111](https://user-images.githubusercontent.com/48037467/56077114-e4a1be80-5e0a-11e9-92be-58771c5e5932.png)

 站点已经开启HTTPS
Bot api 正确         给机器人发二维码的时候一直回复正在解码。
请问这是怎么回事

**Comment by hj-mb** [comment]
改解码方式

**Comment by zs910208565** [comment]
成功了，谢谢
