### ISSUE TITLE
使用单端口后，在线IP数限制好像就失效了。

### ISSUE THREAD

**Issue by yangyzp** [Anankke/ss-panel-v3-mod_Uim#612]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

启用单端口后，在线IP数限制好像就失效了。
举例：限制1个IP，但是测试多个（3个）ip一样可以正常使用，而且面板上显示已经超过ip限制的了（在线ip数：3/1）

**申请添加新的特性或功能或者好的想法**

**Comment by yangyzp** [comment]
补充：我是用 一台电脑网线连接，电信家宽；一步联通手机；一部电信手机  测试的
这里应该是3个设备，3个ip了

**Comment by NimaQu** [comment]
你是管理员账号吧，管理员不受限制的

**Comment by yangyzp001** [comment]
我不是用管理员账号测试的，新建了一个普通账号测试。
没有启用单端口的时候，是生效的
