### ISSUE TITLE
请问如何取消浏览器限制

### ISSUE THREAD

**Issue by lloyd18** [Anankke/ss-panel-v3-mod_Uim#613]
![微信截图_20190416130020](https://user-images.githubusercontent.com/10294460/56183133-aa713080-6047-11e9-8d21-c540faa68d01.jpg)

**Comment by NimaQu** [comment]
@lloyd18 自己看代码，到时候解除了又来问为什么360打开我的网站显示有问题🐴？

**Comment by WooMai** [comment]
@lloyd18 200解决

**Comment by lloyd18** [comment]
> @lloyd18 自己看代码，到时候解除了又来问为什么360打开我的网站显示有问题🐴？

找了半天找不到，习惯了360极速的手势，你告诉我需要修改哪个文件吧

**Comment by lloyd18** [comment]
> @lloyd18 200解决

200过分了啊

**Comment by yry0008** [comment]
自己一个个文件找
把这个删掉
<script src="assets/js/f***.js"></script>
粗话已经被*和谐

**Comment by NimaQu** [comment]
@lloyd18 既然用 360又不会看代码建议使用

https://github.com/ssrpanel/SSRPanel

**Comment by lloyd18** [comment]
> 自己一个个文件找
> 把这个删掉
> 
> <script src="assets/js/f***.js"></script>
> 粗话已经被*和谐

感谢，好了

**Comment by maxwellhouse102** [comment]
@lloyd18 
请问是怎么改好的？修改哪个文件？
