### ISSUE TITLE
面板经常提示节点掉线，但是后端还可以正常上网

### ISSUE THREAD

**Issue by baiyou2014** [Anankke/ss-panel-v3-mod_Uim#621]
**我确认我已经阅读了** (使用 "x" 选择)

- [√ ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ √] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [√ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

十几个节点只有一个是绿色的，其他的都是红色的了，试了试客户端可以正常上网

**Comment by Anankke** [comment]
@baiyou2014 你网不好

**Comment by baiyou2014** [comment]
> @baiyou2014 你网不好
请问大佬是前端的网路不好是吧？

**Comment by Anankke** [comment]
@baiyou2014 那不然呢
去看你的后端 log 了解详情

**Comment by baiyou2014** [comment]
后端用的是一键安装脚本，没注意Log在那个位置，请教大佬指导一下

**Comment by GregTechnology** [comment]
@baiyou2014 100解忧愁

**Comment by Anankke** [comment]
@baiyou2014

**Comment by baiyou2014** [comment]
大佬们都是很有经验啊，佩服哈

**Comment by NimaQu** [comment]
@Anankke ![img](https://i.loli.net/2019/04/25/5cc182e86aa9f.png)

**Comment by baiyou2014** [comment]
两个大佬都来了啊

**Comment by Anankke** [comment]
一键脚本又不是我写的，问我干嘛，要死吖

**Comment by kn007** [comment]
@Anankke 围观下超凶。

**Comment by Anankke** [comment]
自己找找守护的配置应该就有了

**Comment by baiyou2014** [comment]
恩，谢谢了啊。我自己又加了一个supervisort玩意，

**Comment by lsc272** [comment]
> 恩，谢谢了啊。我自己又加了一个supervisort玩意，

我遇到和你一样的问题，supervisor的命令是什么呀？
