### ISSUE TITLE
用户等级为1单端口节点不显示

### ISSUE THREAD

**Issue by Colinwood11** [Anankke/ss-panel-v3-mod_Uim#622]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

经过测试，符合如下条件时，会出现此问题

用户等级1
节点等级1
节点为单端口
只能看得到节点状态 但是不显示节点信息（包括订阅后也没有节点）

当
用户等级2
节点等级1
一切正常

**Comment by Anankke** [comment]
检查承载用户等级

**Comment by Colinwood11** [comment]
承载用户等级为6

**Comment by Colinwood11** [comment]
承载用户等级为666

**Comment by Colinwood11** [comment]
我应该设置为0？

**Comment by Anankke** [comment]
无法复现

**Comment by Colinwood11** [comment]
设置为0是直接都没有了

**Comment by Colinwood11** [comment]
找到问题了    承载用户需要等级越大越好   单端口的那个节点设置直接写0  我之前是2  所以导致的

**Comment by Colinwood11** [comment]
谢谢指点
