### ISSUE TITLE
Job.php 第766-779行是否应该放在一个判断里

### ISSUE THREAD

**Issue by zqcthegreat** [Anankke/ss-panel-v3-mod_Uim#632]
**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

app/Command/Job.php 第766-779行，这部分是不是应该放进一个判断里面？没有装radius的情况下，执行这个浪费时间。

        $rbusers = RadiusBan::all();
        foreach ($rbusers as $sinuser) {
            $user = User::find($sinuser->userid);
            if ($user == null) {
                $sinuser->delete();
                continue;
            }
            if ($user->enable == 1 && (strtotime($user->expire_in) > time() || strtotime($user->expire_in) < 644447105) && $user->transfer_enable > $user->u + $user->d) {
                $sinuser->delete();
                Radius::Add($user, $user->passwd);
            }

**Comment by Anankke** [comment]
radius 没装表里没数据的
你要是开心可以跑 114514 次看看能不能拖慢 114514 秒

**Comment by NimaQu** [comment]
@Anankke ow?

**Comment by Anankke** [comment]
> @Anankke ow?

好，上线

**Comment by zqcthegreat** [comment]
实测，删掉这几行或者加判断之后，一个checkjob的执行时间减少了20秒

**Comment by Anankke** [comment]
可以 pr 一下

**Comment by zqcthegreat** [comment]
print($rbusers); 发现不为空，出来了很多用户。是我自己的问题吗？
