### ISSUE TITLE
如何实现演示站的UI效果

### ISSUE THREAD

**Issue by frystamuzn** [Anankke/ss-panel-v3-mod_Uim#633]
装完后是默认的界面。并没有新界面新UI。

**Comment by NimaQu** [comment]
@frystamuzn 切换至 dev 分支（未全部完成）

**Comment by heitu001** [comment]
> @frystamuzn切换至dev分支（未全部完成）

新的ui背景如何更改~黑黑的不是很好看

**Comment by Anankke** [comment]
> > @frystamuzn切换至dev分支（未全部完成）
> 
> 新的ui背景如何更改~黑黑的不是很好看

https://github.com/Anankke/ss-panel-v3-mod_Uim/issues/637#issuecomment-491445300
