### ISSUE TITLE
新创建的用户会遇到有的节点无法使用（之前创建的老用户，可以正常使用这个新用户没办法使用的节点），需要重启节点之后，新创建的用户才能使用，这个是怎么回事？

### ISSUE THREAD

**Issue by maiyouyou** [Anankke/ss-panel-v3-mod_Uim#635]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**

**Comment by Anankke** [comment]
你后端没同步

**Comment by maiyouyou** [comment]
> 你后端没同步

大佬，我要怎么开启同步呢？我用的是一键对接后端的（有没有好用点的后端对接介绍的，求大佬推荐）

**Comment by Anankke** [comment]
@maiyouyou 自己看 wiki 啊

**Comment by maiyouyou** [comment]
> @maiyouyou自己看wiki啊

哦，好

**Comment by regendsoh** [comment]
@maiyouyou 要是节点1c1g可以试试看docker对接😂

**Comment by maiyouyou** [comment]
> @maiyouyou要是节点1c1g可以试试看泊坞窗对接

好的
