### ISSUE TITLE
今日流量那一栏每天不会重置

### ISSUE THREAD

**Issue by noir1216** [Anankke/ss-panel-v3-mod_Uim#636]
crontab -l 里有  0 0 * * * php -n /home/wwwroot/sspanel/xcat dailyjob   这一项，但是每天不会重置

手动运行php -n /home/wwwroot/sspanel/xcat dailyjob可以重置，但会报错。提示如下：

rm: cannot remove ‘/home/wwwroot/sspanel/storage/*.png’: No such file or directory
From https://github.com/xcxnig/ssr-download
 * branch            HEAD       -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	README.md
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by Anankke** [comment]
看不懂的东西不要瞎改好吗秋梨膏
检查你的文件夹权限或者是否存在，然后把你改了的东西给 reset 了谢谢茄子
