### ISSUE TITLE
speedtest测速bug

### ISSUE THREAD

**Issue by lsbjkc** [Anankke/ss-panel-v3-mod_Uim#639]
有一个游戏节点，后端配置文件设置成0之后，每隔几分钟就测一次速，另一个节点则不会。
视频节点设置12小时测速一次，也是正常，不知道问题出在哪里。。。。
![image](https://user-images.githubusercontent.com/43370337/57576434-57499c80-7492-11e9-9def-c322243573ca.png)
![image](https://user-images.githubusercontent.com/43370337/57576435-5fa1d780-7492-11e9-8aa3-7546f94a663f.png)
![image](https://user-images.githubusercontent.com/43370337/57576438-6892a900-7492-11e9-9d90-eee3c5297c6a.png)

**Comment by Anankke** [comment]
那就用个正常值啊kora

**Comment by lsbjkc** [comment]
会不会是之前卸载过一次后端，但是没卸载掉测速模块导致的

**Comment by Anankke** [comment]
？？？
不是

**Comment by regendsoh** [comment]
@lsbjkc 建议你先
sudo sh stop.sh
sudo sh run.sh

跑一次 再观察
