### ISSUE TITLE
站点地址和订阅地址分开设置产生bug

### ISSUE THREAD

**Issue by lsbjkc** [Anankke/ss-panel-v3-mod_Uim#650]
站点地址和订阅地址不同的情况，面板的订阅地址格式变成：https://sspnel.com/https://sub.com/link/xxxxxx

**Comment by GregTechnology** [comment]
@lsbjkc 我局得你直接把订阅连接前的baseurl改成订阅不就好了（池沼小🍪

**Comment by lsbjkc** [comment]
![image](https://user-images.githubusercontent.com/43370337/57821801-73b44480-77c4-11e9-96f6-604347d813ab.png)
改了之后两个地址就连在一起了。。。。
![image](https://user-images.githubusercontent.com/43370337/57821818-80389d00-77c4-11e9-8cf2-4ded48abd227.png)

**Comment by Anankke** [comment]
你删掉前面的不行？
建议学习 PHP？
脑子有 Bug？

**Comment by regendsoh** [comment]
@lsbjkc 觉得 不会就不要乱改 不要和拿总一个德性 不会还瞎折腾

**Comment by JohnFreeman9** [comment]
@regendsoh 承包我一天的笑点

**Comment by regendsoh** [comment]
@lsbjkc 
拿去
$System_Config['subUrl'] = 'https://www.baidu.com/link/';

**Comment by lsbjkc** [comment]
> @lsbjkc 觉得 不会就不要乱改 不要和拿总一个德性 不会还瞎折腾

就是不会才折腾啊，折腾多了不就会了吗，你生下来就会的吗。。。。

**Comment by regendsoh** [comment]
@lsbjkc 我是作死 但是我的作死是不拿小问题出来问 自己慢慢研究 很多问题谷歌就有
如果你不会php 谷歌去吧。

**Comment by lsbjkc** [comment]
> @lsbjkc
> 拿去
> $System_Config['subUrl'] = 'https://www.baidu.com/link/';

我在提问之前就是这么解决的，如果站点地址放空会不会影响其他功能，比如支付之类的

**Comment by regendsoh** [comment]
@lsbjkc 谁让你站点地址放空啊卧槽。。。

**Comment by laurieryayoi** [comment]
@regendsoh 他们实在不懂baseurl的意思

**Comment by lsbjkc** [comment]
> @lsbjkc 谁让你站点地址放空啊卧槽。。。

是不是说站点地址和订阅地址必须一样吗

**Comment by regendsoh** [comment]
@lsbjkc 假设
站点主要浏览地址是 https://www.google.com
你就设站点地址是 https://www.google.com
要订阅地址是 https://www.baidu.com/link
那么把suburl前面的system config的baseurl去掉写 https://www.baidu.com/link

**Comment by ranwen** [comment]
@lsbjkc 我寻思着你既然要自己乱搞 不应该自己先去认认真真学一学php语言基础吗？ 有其他编程语言基础半小时就能入门 在这里发垃圾issue骚扰开发者有意思？ 如果没有编程基础还想瞎改？

**Comment by lsbjkc** [comment]
> @lsbjkc 假设
> 站点主要浏览地址是 https://www.google.com
> 你就设站点地址是 https://www.google.com
> 要订阅地址是 https://www.baidu.com/link
> 那么把suburl前面的system config的baseurl去掉写 https://www.baidu.com/link

原来baseurl是这么用的，感谢，(づ￣ 3￣)づ

**Comment by regendsoh** [comment]
@lsbjkc 你告诉我
echo $System_Config['baseUrl'];
和
echo $System_Config['subUrl'];
的答案吧

假设 $System_Config['subUrl'] = $System_Config['baseUrl'].'/link';

**Comment by regendsoh** [comment]
@regendsoh $System_Config['baseUrl'] = "https://www.baidu.com"; 的情况下

**Comment by lsbjkc** [comment]
> @lsbjkc 我寻思着你既然要自己乱搞 不应该自己先去认认真真学一学php语言基础吗？ 有其他编程语言基础半小时就能入门 在这里发垃圾issue骚扰开发者有意思？ 如果没有编程基础还想瞎改？

抱歉，文科生对编程语言没有一个系统的概念，都是从边边角角开始摸索，所以很多东西内行看起来是基本操作，我就摸不着头脑。。。。

**Comment by GregTechnology** [comment]
@lsbjkc 不会解决请https://t.me/SSUnion 看群置顶
