### ISSUE TITLE
关于最近V3支付的一些建议

### ISSUE THREAD

**Issue by uim-best** [Anankke/ss-panel-v3-mod_Uim#652]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x ] 申请添加新的特性或功能或者好的想法
这几天圈内发生了这么多事情，
先有doubi大佬的事情，然后秋大也删文了，隔壁的胖虎也删库了；
支付圈先是trimepay终于是宣布“停运一个月”（虽然是tony大佬运营的，但是处于半吊状态也有段时间了），然后来一个新晋的tomatopay运营半个月突然想关站（虽然又被人接盘了）？
尤其是tomatopay的事情，作为旁观者都有点看不下去，看着大家在群里撕逼的撕逼、发恼骚得发恼骚。

我建议下掉像tomatopay这样不成熟的支付，或者说新晋的支付在接入uim前先亮一手家底？

**Comment by AS137443** [comment]
@uim-best 除非代码有明确的冲突关系，不然支付的接入是一码事，用户的选择是另一回事。

**Comment by Anankke** [comment]
比较赞同。
正因如此，我们在多方面考虑之后，并没有合并两家新的支付。

**Comment by uim-best** [comment]
> @uim-best 除非代码有明确的冲突关系，不然支付的接入是一码事，用户的选择是另一回事。

course，接入支付跟使用者是否使用没关系；只是对于这种类似的支付或许可以考虑不并入进来，
就像Anankke 说的
（个人建议，如有误请大佬轻喷）

**Comment by SakuraSa233** [comment]
Why not build a callable module interface? Then no one would complain about payment system.

**Comment by CrazyBoyM** [comment]
或许可以考虑在项目中直接加入国际数字货币的支付方式，而用户可以根据教程指引去第三方平台把支付宝或微信转换成该货币再支付给网站，管理员在配置文件中填上自己钱包地址

**Comment by Anankke** [comment]
没听懂
