### ISSUE TITLE
重定向问题

### ISSUE THREAD

**Issue by doudou9418** [Anankke/ss-panel-v3-mod_Uim#656]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容
debug内容：
RuntimeException thrown with message "Callable Slim\App\Controllers\HomeController does not exist"

Stacktrace:
#16 RuntimeException in /www/wwwroot/sspanel/vendor/slim/slim/Slim/CallableResolver.php:90
#15 Slim\CallableResolver:resolveCallable in /www/wwwroot/sspanel/vendor/slim/slim/Slim/CallableResolver.php:61
#14 Slim\CallableResolver:resolve in /www/wwwroot/ssspanel/vendor/slim/slim/Slim/CallableResolverAwareTrait.php:45
#13 Slim\Routable:resolveCallable in /www/wwwroot/sspanel/vendor/slim/slim/Slim/Route.php:351
#12 Slim\Route:__invoke in /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#11 Slim\Route:callMiddlewareStack in /www/wwwroot/sspanel/vendor/slim/slim/Slim/Route.php:334
#10 Slim\Route:run in /www/wwwroot/sspanel/vendor/slim/slim/Slim/App.php:515
#9 Slim\App:__invoke in /www/wwwroot/sspanel/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php:70
#8 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in /www/wwwroot/sspanel/vendor/slim/slim/Slim/DeferredCallable.php:43
#7 call_user_func_array in /www/wwwroot/sspanel/vendor/slim/slim/Slim/DeferredCallable.php:43
#6 Slim\DeferredCallable:__invoke in /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#5 call_user_func in /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#4 Slim\App:Slim\{closure} in /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#3 Slim\App:callMiddlewareStack in /www/wwwroot/sspanel/vendor/slim/slim/Slim/App.php:406
#2 Slim\App:process in /www/wwwroot/sspanel/vendor/slim/slim/Slim/App.php:314
#1 Slim\App:run in /www/wwwroot/sspanel/config/routes.php:383
#0 require in /www/wwwroot/sspanel/public/index.php:11

我看了一下HomeController文件是存在的呀，用F12查看Network查看不断请求500页面，google半天没找到问题所在，麻烦大佬看一下，帮忙解决一下，谢谢！

**申请添加新的特性或功能或者好的想法**

**Comment by Anankke** [comment]
正在修复

**Comment by doudou9418** [comment]
好的，多谢！

**Comment by Anankke** [comment]
如果着急可以先 reset 到今天之前的 commit

**Comment by doudou9418** [comment]
嗯，好的，辛苦您了

**Comment by Anankke** [comment]
fixed

**Comment by 5864048** [comment]
我也是重定向过多。咋解决。

**Comment by Anankke** [comment]
> 我也是重定向过多。咋解决。

rm -rf /

**Comment by regendsoh** [comment]
@Anankke 宝塔是不是打开了强制https。

**Comment by 5864048** [comment]
rm -rf/ 直接这个命令？
