### ISSUE TITLE
最新版添加公告的问题

### ISSUE THREAD

**Issue by wuyaiii** [Anankke/ss-panel-v3-mod_Uim#662]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容
commit 7b0b30ce0afce95437baff78e0de1cd0a4c36380
Merge: f81b1cd 4e87da9
Author: Anankke <anankke@protonmail.com>
Date:   Tue May 21 03:40:49 2019 -0400

    Merge pull request #657 from SukkaW/dev
    
    Refactor: perfops & compress images

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容
![QQ截图20190526223748](https://user-images.githubusercontent.com/50183639/58383249-e912e700-8006-11e9-8bf6-1ff77cd2f0d6.png)
![QQ截图20190526223837](https://user-images.githubusercontent.com/50183639/58383258-0c3d9680-8007-11e9-9179-0c121c0b600c.png)

半个多月前搭建的面板没问题，这两天装的才出现这个状况，反复装了3次 同样都是管理公告那里添加不了

**申请添加新的特性或功能或者好的想法**

**Comment by Anankke** [comment]
PHP 本地日志看看
