### ISSUE TITLE
Installed theme does not match the one in the demo

### ISSUE THREAD

**Issue by brswww** [Anankke/ss-panel-v3-mod_Uim#666]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x ] 申请添加新的特性或功能或者好的想法

Hi I just registered Telegram but it ask 50$ for the entrance of group, not sure the reason. Not mean to bordering. 

My proposal is the theme in the demo look very nice but when i fully install the Panel the dark theme does not comes out. 

Maybe leave a link of the theme in the demo for ppl to download, it look very nice.

Plus please leave email address or other common IM in README so that ppl do not need writting issues to reaching the dev team. I understanded that this post may 'polluted' hundreds of followers' inbox, please forgive. Thank you.

**Comment by WooMai** [comment]
@brswww ？？？

**Comment by NimaQu** [comment]
@brswww the dark theme is only available in dev branch, may you need switch to dev branch
